CREATE DATABASE moneysavingsdb;

USE moneysavingsdb;
DROP DATABASE moneysavingsdb;
CREATE TABLE history(
	ID 				int 			PRIMARY KEY 		AUTO_INCREMENT,
    TIMEDATE 		datetime 		UNIQUE 				DEFAULT CURRENT_TIMESTAMP,
	ACTION 			boolean 		NOT NULL 			DEFAULT 0,
    AMOUNT 			double(7, 2) 	NOT NULL 			DEFAULT 0.00,
    DESCRIPTION 	varchar(1000) 	NOT NULL 			DEFAULT ""
);


-- INSERT INTO history (TIMEDATE, ACTION, AMOUNT, DESCRIPTION) VALUES ("2025-02-15 10:35:43", 1, 1337, "custom date");
-- INSERT INTO history (ACTION, AMOUNT, DESCRIPTION) VALUES (0, 43.23, "default value");
-- INSERT INTO history (ACTION, AMOUNT, DESCRIPTION) VALUES (1, 542.11, "default value 1");

-- DESCRIBE history;
-- SELECT * from history;
SELECT * FROM history ORDER BY TIMEDATE DESC; 

-- SELECT SUM(AMOUNT) FROM history WHERE ACTION=0;
-- SELECT SUM(AMOUNT) FROM history WHERE ACTION=1;


-- ALTER TABLE history DROP CONSTRAINT TIMEDATE;
-- ALTER TABLE history DROP CONSTRAINT ID;
-- ALTER TABLE history ADD CONSTRAINT PRIMARY KEY (TIMEDATE);
-- ALTER TABLE history ADD CONSTRAINT UNIQUE (TIMEDATE);

